authors:
  randar:
    name: Randy Rowland
    description: Creator
    avatar: https://randyrowland.me/authors/admin/avatar_hube6c5e4d23d98f5dd9aa9c05792282c2_1893342_270x270_fill_q90_lanczos_center.jpg